package model.EO;

import model.EO.common.AppModuleAM;

import model.customer.UVO.OpportunitiesUVOImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 24 15:40:42 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl implements AppModuleAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for ProductsU1.
     * @return ProductsU1
     */
    public ViewObjectImpl getProductsU1() {
        return (ViewObjectImpl) findViewObject("ProductsU1");
    }

    /**
     * Container's getter for CustomersU1.
     * @return CustomersU1
     */
    public ViewObjectImpl getCustomersU1() {
        return (ViewObjectImpl) findViewObject("CustomersU1");
    }

    /**
     * Container's getter for NotesU1.
     * @return NotesU1
     */
    public ViewObjectImpl getNotesU1() {
        return (ViewObjectImpl) findViewObject("NotesU1");
    }

    /**
     * Container's getter for TasksU1.
     * @return TasksU1
     */
    public ViewObjectImpl getTasksU1() {
        return (ViewObjectImpl) findViewObject("TasksU1");
    }

    /**
     * Container's getter for ContactsU2.
     * @return ContactsU2
     */
    public ViewObjectImpl getContactsU2() {
        return (ViewObjectImpl) findViewObject("ContactsU2");
    }

    /**
     * Container's getter for AppointmentsU3.
     * @return AppointmentsU3
     */
    public ViewObjectImpl getAppointmentsU3() {
        return (ViewObjectImpl) findViewObject("AppointmentsU3");
    }

    /**
     * Container's getter for OpportunitiesU1.
     * @return OpportunitiesU1
     */
    public OpportunitiesUVOImpl getOpportunitiesU1() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU1");
    }

    /**
     * Container's getter for OpportunitiesU2.
     * @return OpportunitiesU2
     */
    public OpportunitiesUVOImpl getOpportunitiesU2() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU2");
    }

    /**
     * Container's getter for TasksU2.
     * @return TasksU2
     */
    public ViewObjectImpl getTasksU2() {
        return (ViewObjectImpl) findViewObject("TasksU2");
    }

    /**
     * Container's getter for CustomersU3.
     * @return CustomersU3
     */
    public ViewObjectImpl getCustomersU3() {
        return (ViewObjectImpl) findViewObject("CustomersU3");
    }

    /**
     * Container's getter for RevenueItems1.
     * @return RevenueItems1
     */
    public ViewObjectImpl getRevenueItems1() {
        return (ViewObjectImpl) findViewObject("RevenueItems1");
    }

    /**
     * Container's getter for ContactsU3.
     * @return ContactsU3
     */
    public ViewObjectImpl getContactsU3() {
        return (ViewObjectImpl) findViewObject("ContactsU3");
    }

    /**
     * Container's getter for OpportunitiesU4.
     * @return OpportunitiesU4
     */
    public OpportunitiesUVOImpl getOpportunitiesU4() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU4");
    }

    /**
     * Container's getter for AppointmentsU1.
     * @return AppointmentsU1
     */
    public ViewObjectImpl getAppointmentsU1() {
        return (ViewObjectImpl) findViewObject("AppointmentsU1");
    }

    /**
     * Container's getter for AppointmentsU2.
     * @return AppointmentsU2
     */
    public ViewObjectImpl getAppointmentsU2() {
        return (ViewObjectImpl) findViewObject("AppointmentsU2");
    }

    /**
     * Container's getter for NotesU2.
     * @return NotesU2
     */
    public ViewObjectImpl getNotesU2() {
        return (ViewObjectImpl) findViewObject("NotesU2");
    }

    /**
     * Container's getter for TasksU3.
     * @return TasksU3
     */
    public ViewObjectImpl getTasksU3() {
        return (ViewObjectImpl) findViewObject("TasksU3");
    }

    /**
     * Container's getter for CustomersU2.
     * @return CustomersU2
     */
    public ViewObjectImpl getCustomersU2() {
        return (ViewObjectImpl) findViewObject("CustomersU2");
    }

    /**
     * Container's getter for ContactsU1.
     * @return ContactsU1
     */
    public ViewObjectImpl getContactsU1() {
        return (ViewObjectImpl) findViewObject("ContactsU1");
    }

    /**
     * Container's getter for OpportunitiesU3.
     * @return OpportunitiesU3
     */
    public OpportunitiesUVOImpl getOpportunitiesU3() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU3");
    }

    /**
     * Container's getter for CustomersU4.
     * @return CustomersU4
     */
    public ViewObjectImpl getCustomersU4() {
        return (ViewObjectImpl) findViewObject("CustomersU4");
    }

    /**
     * Container's getter for CustomerToNotes.
     * @return CustomerToNotes
     */
    public ViewLinkImpl getCustomerToNotes() {
        return (ViewLinkImpl) findViewLink("CustomerToNotes");
    }

    /**
     * Container's getter for CusotmersToTasksVL1.
     * @return CusotmersToTasksVL1
     */
    public ViewLinkImpl getCusotmersToTasksVL1() {
        return (ViewLinkImpl) findViewLink("CusotmersToTasksVL1");
    }

    /**
     * Container's getter for CustomerToContactsVL1.
     * @return CustomerToContactsVL1
     */
    public ViewLinkImpl getCustomerToContactsVL1() {
        return (ViewLinkImpl) findViewLink("CustomerToContactsVL1");
    }

    /**
     * Container's getter for CustomerToAppointmentsVL1.
     * @return CustomerToAppointmentsVL1
     */
    public ViewLinkImpl getCustomerToAppointmentsVL1() {
        return (ViewLinkImpl) findViewLink("CustomerToAppointmentsVL1");
    }

    /**
     * Container's getter for CustomerToOpportunityVL1.
     * @return CustomerToOpportunityVL1
     */
    public ViewLinkImpl getCustomerToOpportunityVL1() {
        return (ViewLinkImpl) findViewLink("CustomerToOpportunityVL1");
    }

    /**
     * Container's getter for TasksOppurtunityVL1.
     * @return TasksOppurtunityVL1
     */
    public ViewLinkImpl getTasksOppurtunityVL1() {
        return (ViewLinkImpl) findViewLink("TasksOppurtunityVL1");
    }

    /**
     * Container's getter for CustomerToOpportunityVL2.
     * @return CustomerToOpportunityVL2
     */
    public ViewLinkImpl getCustomerToOpportunityVL2() {
        return (ViewLinkImpl) findViewLink("CustomerToOpportunityVL2");
    }

    /**
     * Container's getter for OpportuntiesToRevenueItemsVL1.
     * @return OpportuntiesToRevenueItemsVL1
     */
    public ViewLinkImpl getOpportuntiesToRevenueItemsVL1() {
        return (ViewLinkImpl) findViewLink("OpportuntiesToRevenueItemsVL1");
    }

    /**
     * Container's getter for OpportunityToContactsVL1.
     * @return OpportunityToContactsVL1
     */
    public ViewLinkImpl getOpportunityToContactsVL1() {
        return (ViewLinkImpl) findViewLink("OpportunityToContactsVL1");
    }

    /**
     * Container's getter for OpportunitiesToAppointmentsVL.
     * @return OpportunitiesToAppointmentsVL
     */
    public ViewLinkImpl getOpportunitiesToAppointmentsVL() {
        return (ViewLinkImpl) findViewLink("OpportunitiesToAppointmentsVL");
    }

    /**
     * Container's getter for OpportunitiesToAppointmentsVL1.
     * @return OpportunitiesToAppointmentsVL1
     */
    public ViewLinkImpl getOpportunitiesToAppointmentsVL1() {
        return (ViewLinkImpl) findViewLink("OpportunitiesToAppointmentsVL1");
    }

    /**
     * Container's getter for OpportunitiesToNotesL1.
     * @return OpportunitiesToNotesL1
     */
    public ViewLinkImpl getOpportunitiesToNotesL1() {
        return (ViewLinkImpl) findViewLink("OpportunitiesToNotesL1");
    }

    /**
     * Container's getter for CusotmersToTasksVL2.
     * @return CusotmersToTasksVL2
     */
    public ViewLinkImpl getCusotmersToTasksVL2() {
        return (ViewLinkImpl) findViewLink("CusotmersToTasksVL2");
    }

    /**
     * Container's getter for OpportunityToContactsVL2.
     * @return OpportunityToContactsVL2
     */
    public ViewLinkImpl getOpportunityToContactsVL2() {
        return (ViewLinkImpl) findViewLink("OpportunityToContactsVL2");
    }

    /**
     * Container's getter for CustomerToContactsVL2.
     * @return CustomerToContactsVL2
     */
    public ViewLinkImpl getCustomerToContactsVL2() {
        return (ViewLinkImpl) findViewLink("CustomerToContactsVL2");
    }
    
    
    
    
    public void populate_Intersection(Integer rId,Integer bId) {
        
    ViewObjectImpl vo=this.getCustomersContactsU1();
    Row row=vo.createRow();
    
    row.setAttribute("RId",rId);
    row.setAttribute("BId", bId);
    vo.insertRow(row);
    
    this.getDBTransaction().commit();
  //  this.get
    
   // this.getCustomersU1().executeQuery();
   // this.getContactsU1().executeQuery();
    
    }

    /**
     * Container's getter for CustomersContactsU1.
     * @return CustomersContactsU1
     */
    public ViewObjectImpl getCustomersContactsU1() {
        return (ViewObjectImpl) findViewObject("CustomersContactsU1");
    }
}

