CREATE OR REPLACE TRIGGER ADDRESS_TRG 
BEFORE INSERT ON ADDRESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADDRESS_ID IS NULL THEN
      SELECT ADDRESS_SEQ.NEXTVAL INTO :NEW.ADDRESS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
