CREATE OR REPLACE TRIGGER APPOINTMENTS_TRG 
BEFORE INSERT ON APPOINTMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.APPOINTMENT_ID IS NULL THEN
      SELECT APPOINTMENTS_SEQ.NEXTVAL INTO :NEW.APPOINTMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
