CREATE OR REPLACE TRIGGER CONTACTS_TRG 
BEFORE INSERT ON CONTACTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CONTACT_ID IS NULL THEN
      SELECT CONTACTS_SEQ.NEXTVAL INTO :NEW.CONTACT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
