CREATE OR REPLACE TRIGGER LOOKUPS_TRG 
BEFORE INSERT ON LOOKUPS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOOKUP_ID IS NULL THEN
      SELECT LOOKUPS_SEQ.NEXTVAL INTO :NEW.LOOKUP_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
