CREATE OR REPLACE TRIGGER NOTES_TRG 
BEFORE INSERT ON NOTES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NOTES_ID IS NULL THEN
      SELECT NOTES_SEQ.NEXTVAL INTO :NEW.NOTES_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
