package model.docs.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 22 22:49:31 IST 2017
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    void setFileData(Long docId, Long opptId, String name, String path);
}

