package model.RVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 15 15:16:46 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RoleNameLookupImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RoleNameLookupImpl() {
    }
}

