package model.lookup;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 26 23:33:08 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DirectionLookupImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DirectionLookupImpl() {
    }
}

