package model.lookup;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 27 00:24:55 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PriorityLookupImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PriorityLookupImpl() {
    }
}

