package model.customer.UVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 20 08:00:43 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContactsOpportunitiesUVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContactsOpportunitiesUVOImpl() {
    }
    
    
    /**
     * Returns the variable value for jobIdVar.
     * @return variable value for jobIdVar
     */
    public String getjobIdVar() {
        return (String) ensureVariableManager().getVariableValue("jobIdVar");
    }

    /**
     * Sets <code>value</code> for variable jobIdVar.
     * @param value value to bind as jobIdVar
     */
    public void setjobIdVar(String value) {
        ensureVariableManager().setVariableValue("jobIdVar", value);
    }
}

