package model.customer.UVO;

import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 22 02:43:16 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContactTabUVORowImpl extends ViewRowImpl {
    public static final int ENTITY_CONTACTEO = 0;
    public static final int ENTITY_CUSTOMERCONTACTEO = 1;
    public static final int ENTITY_CUSTOMEREO = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BuyingRoleId,
        AddressId,
        ContactId,
        CreatedBy,
        CreatedOn,
        DepartmentNameId,
        Email,
        FirstName,
        InfluenceLevelId,
        IsActive,
        IsPrimary,
        LastName,
        LastUpdatedBy,
        LastUpdatedOn,
        VersionNo,
        MobilePhone,
        WorkPhone,
        CustomerId,
        CustomerName,
        CustomerId1,
        Ceo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BUYINGROLEID = AttributesEnum.BuyingRoleId.index();
    public static final int ADDRESSID = AttributesEnum.AddressId.index();
    public static final int CONTACTID = AttributesEnum.ContactId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int DEPARTMENTNAMEID = AttributesEnum.DepartmentNameId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int INFLUENCELEVELID = AttributesEnum.InfluenceLevelId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int ISPRIMARY = AttributesEnum.IsPrimary.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDON = AttributesEnum.LastUpdatedOn.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int MOBILEPHONE = AttributesEnum.MobilePhone.index();
    public static final int WORKPHONE = AttributesEnum.WorkPhone.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CUSTOMERID1 = AttributesEnum.CustomerId1.index();
    public static final int CEO = AttributesEnum.Ceo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ContactTabUVORowImpl() {
    }
}

