package model.EO.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 24 16:01:56 IST 2017
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    void populate_Intersection(Integer rId, Integer bId);
}

