package model.customer.EO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 23 06:03:57 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MasterOppReveueVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MasterOppReveueVOImpl() {
    }
}

