package model.customer.EO;

import java.math.BigDecimal;

import java.sql.SQLException;
import java.sql.Timestamp;

import java.util.Calendar;

import java.util.Date;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 22 13:03:26 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OpportunityEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        OpportunityId,
        CustomerId,
        WinProbablity,
        StartDate,
        EndDate,
        SalesStageId,
        SalesMethodId,
        SalesChannelId,
        Revenue,
        BestCaseRevenue,
        WorstCaseRevenue,
        IsBudgeted,
        BudgetAmount,
        EstimatedDurationInDays,
        RiskLevel,
        IsIncluded,
        CreatedById,
        IsSuccess,
        PrimaryContact,
        CreatedBy,
        CreatedOn,
        LastUpdatedBy,
        LastUpdatedOn,
        VersionNo,
        IsActive,
        DecisionLevelId,
        OppurtunityName,
        QuarterNo,
        OpportunityDoc,
        Task,
        ContactOpportunity;
        private static AttributesEnum[] vals = null;

        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    // public static final int QUARTERNUMBER = AttributesEnum.QuarterNumber.index();


    public static final int OPPORTUNITYID = AttributesEnum.OpportunityId.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int WINPROBABLITY = AttributesEnum.WinProbablity.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int SALESSTAGEID = AttributesEnum.SalesStageId.index();
    public static final int SALESMETHODID = AttributesEnum.SalesMethodId.index();
    public static final int SALESCHANNELID = AttributesEnum.SalesChannelId.index();
    public static final int REVENUE = AttributesEnum.Revenue.index();
    public static final int BESTCASEREVENUE = AttributesEnum.BestCaseRevenue.index();
    public static final int WORSTCASEREVENUE = AttributesEnum.WorstCaseRevenue.index();
    public static final int ISBUDGETED = AttributesEnum.IsBudgeted.index();
    public static final int BUDGETAMOUNT = AttributesEnum.BudgetAmount.index();
    public static final int ESTIMATEDDURATIONINDAYS = AttributesEnum.EstimatedDurationInDays.index();
    public static final int RISKLEVEL = AttributesEnum.RiskLevel.index();
    public static final int ISINCLUDED = AttributesEnum.IsIncluded.index();
    public static final int CREATEDBYID = AttributesEnum.CreatedById.index();
    public static final int ISSUCCESS = AttributesEnum.IsSuccess.index();
    public static final int PRIMARYCONTACT = AttributesEnum.PrimaryContact.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDON = AttributesEnum.LastUpdatedOn.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int DECISIONLEVELID = AttributesEnum.DecisionLevelId.index();
    public static final int OPPURTUNITYNAME = AttributesEnum.OppurtunityName.index();
    public static final int QUARTERNO = AttributesEnum.QuarterNo.index();
    public static final int OPPORTUNITYDOC = AttributesEnum.OpportunityDoc.index();
    public static final int TASK = AttributesEnum.Task.index();
    public static final int CONTACTOPPORTUNITY = AttributesEnum.ContactOpportunity.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OpportunityEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.customer.EO.OpportunityEO");
    }


    /**
     * Gets the attribute value for OpportunityId, using the alias name OpportunityId.
     * @return the value of OpportunityId
     */
    public DBSequence getOpportunityId() {
        return (DBSequence) getAttributeInternal(OPPORTUNITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpportunityId.
     * @param value value to set the OpportunityId
     */
    public void setOpportunityId(DBSequence value) {
        setAttributeInternal(OPPORTUNITYID, value);
    }

    /**
     * Gets the attribute value for CustomerId, using the alias name CustomerId.
     * @return the value of CustomerId
     */
    public Long getCustomerId() {
        return (Long) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerId.
     * @param value value to set the CustomerId
     */
    public void setCustomerId(Long value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for WinProbablity, using the alias name WinProbablity.
     * @return the value of WinProbablity
     */
    public BigDecimal getWinProbablity() {
        return (BigDecimal) getAttributeInternal(WINPROBABLITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WinProbablity.
     * @param value value to set the WinProbablity
     */
    public void setWinProbablity(BigDecimal value) {
        setAttributeInternal(WINPROBABLITY, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the value of EndDate
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
      //  populateAttribute(QUARTERNUMBER, null,true,false,false);
        
    }

    /**
     * Gets the attribute value for SalesStageId, using the alias name SalesStageId.
     * @return the value of SalesStageId
     */
    public Long getSalesStageId() {
        return (Long) getAttributeInternal(SALESSTAGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesStageId.
     * @param value value to set the SalesStageId
     */
    public void setSalesStageId(Long value) {
        setAttributeInternal(SALESSTAGEID, value);
    }

    /**
     * Gets the attribute value for SalesMethodId, using the alias name SalesMethodId.
     * @return the value of SalesMethodId
     */
    public Long getSalesMethodId() {
        return (Long) getAttributeInternal(SALESMETHODID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesMethodId.
     * @param value value to set the SalesMethodId
     */
    public void setSalesMethodId(Long value) {
        setAttributeInternal(SALESMETHODID, value);
    }

    /**
     * Gets the attribute value for SalesChannelId, using the alias name SalesChannelId.
     * @return the value of SalesChannelId
     */
    public Long getSalesChannelId() {
        return (Long) getAttributeInternal(SALESCHANNELID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesChannelId.
     * @param value value to set the SalesChannelId
     */
    public void setSalesChannelId(Long value) {
        setAttributeInternal(SALESCHANNELID, value);
    }

    /**
     * Gets the attribute value for Revenue, using the alias name Revenue.
     * @return the value of Revenue
     */
    public BigDecimal getRevenue() {
        return (BigDecimal) getAttributeInternal(REVENUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Revenue.
     * @param value value to set the Revenue
     */
    public void setRevenue(BigDecimal value) {
        setAttributeInternal(REVENUE, value);
    }

    /**
     * Gets the attribute value for BestCaseRevenue, using the alias name BestCaseRevenue.
     * @return the value of BestCaseRevenue
     */
    public BigDecimal getBestCaseRevenue() {
        return (BigDecimal) getAttributeInternal(BESTCASEREVENUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BestCaseRevenue.
     * @param value value to set the BestCaseRevenue
     */
    public void setBestCaseRevenue(BigDecimal value) {
        setAttributeInternal(BESTCASEREVENUE, value);
    }

    /**
     * Gets the attribute value for WorstCaseRevenue, using the alias name WorstCaseRevenue.
     * @return the value of WorstCaseRevenue
     */
    public BigDecimal getWorstCaseRevenue() {
        return (BigDecimal) getAttributeInternal(WORSTCASEREVENUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorstCaseRevenue.
     * @param value value to set the WorstCaseRevenue
     */
    public void setWorstCaseRevenue(BigDecimal value) {
        setAttributeInternal(WORSTCASEREVENUE, value);
    }

    /**
     * Gets the attribute value for IsBudgeted, using the alias name IsBudgeted.
     * @return the value of IsBudgeted
     */
    public String getIsBudgeted() {
        return (String) getAttributeInternal(ISBUDGETED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsBudgeted.
     * @param value value to set the IsBudgeted
     */
    public void setIsBudgeted(String value) {
        setAttributeInternal(ISBUDGETED, value);
    }

    /**
     * Gets the attribute value for BudgetAmount, using the alias name BudgetAmount.
     * @return the value of BudgetAmount
     */
    public BigDecimal getBudgetAmount() {
        return (BigDecimal) getAttributeInternal(BUDGETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetAmount.
     * @param value value to set the BudgetAmount
     */
    public void setBudgetAmount(BigDecimal value) {
        setAttributeInternal(BUDGETAMOUNT, value);
    }

    /**
     * Gets the attribute value for EstimatedDurationInDays, using the alias name EstimatedDurationInDays.
     * @return the value of EstimatedDurationInDays
     */
    public Long getEstimatedDurationInDays() {
        return (Long) getAttributeInternal(ESTIMATEDDURATIONINDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstimatedDurationInDays.
     * @param value value to set the EstimatedDurationInDays
     */
    public void setEstimatedDurationInDays(Long value) {
        setAttributeInternal(ESTIMATEDDURATIONINDAYS, value);
    }

    /**
     * Gets the attribute value for RiskLevel, using the alias name RiskLevel.
     * @return the value of RiskLevel
     */
    public String getRiskLevel() {
        return (String) getAttributeInternal(RISKLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for RiskLevel.
     * @param value value to set the RiskLevel
     */
    public void setRiskLevel(String value) {
        setAttributeInternal(RISKLEVEL, value);
    }

    /**
     * Gets the attribute value for IsIncluded, using the alias name IsIncluded.
     * @return the value of IsIncluded
     */
    public String getIsIncluded() {
        return (String) getAttributeInternal(ISINCLUDED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsIncluded.
     * @param value value to set the IsIncluded
     */
    public void setIsIncluded(String value) {
        setAttributeInternal(ISINCLUDED, value);
    }

    /**
     * Gets the attribute value for CreatedById, using the alias name CreatedById.
     * @return the value of CreatedById
     */
    public Long getCreatedById() {
        return (Long) getAttributeInternal(CREATEDBYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedById.
     * @param value value to set the CreatedById
     */
    public void setCreatedById(Long value) {
        setAttributeInternal(CREATEDBYID, value);
    }

    /**
     * Gets the attribute value for IsSuccess, using the alias name IsSuccess.
     * @return the value of IsSuccess
     */
    public String getIsSuccess() {
        return (String) getAttributeInternal(ISSUCCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSuccess.
     * @param value value to set the IsSuccess
     */
    public void setIsSuccess(String value) {
        setAttributeInternal(ISSUCCESS, value);
    }

    /**
     * Gets the attribute value for PrimaryContact, using the alias name PrimaryContact.
     * @return the value of PrimaryContact
     */
    public Long getPrimaryContact() {
        return (Long) getAttributeInternal(PRIMARYCONTACT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrimaryContact.
     * @param value value to set the PrimaryContact
     */
    public void setPrimaryContact(Long value) {
        setAttributeInternal(PRIMARYCONTACT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the value of CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdatedOn, using the alias name LastUpdatedOn.
     * @return the value of LastUpdatedOn
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDON);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the value of VersionNo
     */
    public Long getVersionNo() {
        return (Long) getAttributeInternal(VERSIONNO);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for DecisionLevelId, using the alias name DecisionLevelId.
     * @return the value of DecisionLevelId
     */
    public Long getDecisionLevelId() {
        return (Long) getAttributeInternal(DECISIONLEVELID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DecisionLevelId.
     * @param value value to set the DecisionLevelId
     */
    public void setDecisionLevelId(Long value) {
        setAttributeInternal(DECISIONLEVELID, value);
    }

    /**
     * Gets the attribute value for OppurtunityName, using the alias name OppurtunityName.
     * @return the value of OppurtunityName
     */
    public String getOppurtunityName() {
        return (String) getAttributeInternal(OPPURTUNITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for OppurtunityName.
     * @param value value to set the OppurtunityName
     */
    public void setOppurtunityName(String value) {
        setAttributeInternal(OPPURTUNITYNAME, value);
    }

    /**
     * Gets the attribute value for QuarterNumber, using the alias name QuarterNumber.
     * @return the value of QuarterNumber
     */
//    public Number getQuarterNumber() {
//        Timestamp ts = getEndDate();
//        Calendar cal = Calendar.getInstance();
//        cal.setTime(new Date(ts.getTime()));
//        int year = cal.get(Calendar.YEAR);
//        int month = cal.get(Calendar.MONTH);
//        int day = cal.get(Calendar.DAY_OF_MONTH);
//        if (year==2017 && month<=3){  Integer i=  1;
//            try {
//                return new Number(i);
//            } catch (SQLException e) {  e.printStackTrace();
//            }
//        }
//        
//        else if (year==2017 && month>3 && month<=6){  Integer i=  2;
//            try {
//                return new Number(i);
//            } catch (SQLException e) {  e.printStackTrace();
//            }
//        }
//        else if (year==2017 && month>6 && month<=9){  Integer i=  3;
//            try {
//                return new Number(i);
//            } catch (SQLException e) {  e.printStackTrace();
//            }
//        }
//        
//        else if (year==2017 && month>9 && month<=12){  Integer i=  4;
//            try {
//                return new Number(i);
//            } catch (SQLException e) {  e.printStackTrace();
//            }
//        }
//        
//        return null;
//        //return (Number) getAttributeInternal(QUARTERNUMBER);
//    }

    /**
     * Sets <code>value</code> as the attribute value for QuarterNumber.
     * @param value value to set the QuarterNumber
     */
//    public void setQuarterNumber(Number value) {
//        
//        setAttributeInternal(QUARTERNUMBER, value);
//    }

    /**
     * Gets the attribute value for QuarterNo, using the alias name QuarterNo.
     * @return the value of QuarterNo
     */
    public Integer getQuarterNo() {
        return (Integer) getAttributeInternal(QUARTERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for QuarterNo.
     * @param value value to set the QuarterNo
     */
    public void setQuarterNo(Integer value) {
        setAttributeInternal(QUARTERNO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getOpportunityDoc() {
        return (RowIterator) getAttributeInternal(OPPORTUNITYDOC);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTask() {
        return (RowIterator) getAttributeInternal(TASK);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getContactOpportunity() {
        return (RowIterator) getAttributeInternal(CONTACTOPPORTUNITY);
    }

    /**
     * @param opportunityId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence opportunityId) {
        return new Key(new Object[] { opportunityId });
    }


}

