package model.docs;


import model.docs.common.AppModuleAM;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 22 22:13:25 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl implements AppModuleAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for OpportunityDocs1.
     * @return OpportunityDocs1
     */
    public ViewObjectImpl getOpportunityDocs1() {
        return (ViewObjectImpl) findViewObject("OpportunityDocs1");
    }
    
    public void setFileData(Long docId, Long opptId, String name, String path) {
        System.out.println("in AM name: " + name + " path: " + path);
        ViewObject fileVo = this.getOpportunityDocs1();    //OpportunityDocs
        Row newRow = fileVo.createRow();
        newRow.setAttribute("DocId", docId);
        newRow.setAttribute("OpportunityId", opptId);
        newRow.setAttribute("DocName", name);   //Create in DB

        newRow.setAttribute("Path", path);

        fileVo.insertRow(newRow);

        this.getDBTransaction().commit();

        fileVo.executeQuery();
            
        }
}

