package model.AM;

import model.RVO.ProductCountVOImpl;
import model.RVO.RoleNameLookupImpl;
import model.RVO.UserCountVOImpl;

import model.customer.UVO.OpportunitiesUVOImpl;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 22 20:49:08 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for UsersU1.
     * @return UsersU1
     */
    public ViewObjectImpl getUsersU1() {
        return (ViewObjectImpl) findViewObject("UsersU1");
    }

    /**
     * Container's getter for UsersR1.
     * @return UsersR1
     */
    public ViewObjectImpl getUsersR1() {
        return (ViewObjectImpl) findViewObject("UsersR1");
    }

    /**
     * Container's getter for UsersU2.
     * @return UsersU2
     */
    public ViewObjectImpl getUsersU2() {
        return (ViewObjectImpl) findViewObject("UsersU2");
    }

    /**
     * Container's getter for UsersR2.
     * @return UsersR2
     */
    public ViewObjectImpl getUsersR2() {
        return (ViewObjectImpl) findViewObject("UsersR2");
    }

    /**
     * Container's getter for RolesU1.
     * @return RolesU1
     */
    public ViewObjectImpl getRolesU1() {
        return (ViewObjectImpl) findViewObject("RolesU1");
    }

    /**
     * Container's getter for RolesR1.
     * @return RolesR1
     */
    public ViewObjectImpl getRolesR1() {
        return (ViewObjectImpl) findViewObject("RolesR1");
    }

    /**
     * Container's getter for RoleNameLookup1.
     * @return RoleNameLookup1
     */
    public RoleNameLookupImpl getRoleNameLookup1() {
        return (RoleNameLookupImpl) findViewObject("RoleNameLookup1");
    }

    /**
     * Container's getter for UsersU3.
     * @return UsersU3
     */
    public ViewObjectImpl getUsersU3() {
        return (ViewObjectImpl) findViewObject("UsersU3");
    }

    /**
     * Container's getter for UsersRolesU1.
     * @return UsersRolesU1
     */
    public ViewObjectImpl getUsersRolesU1() {
        return (ViewObjectImpl) findViewObject("UsersRolesU1");
    }

    /**
     * Container's getter for ProductCategoryLookup1.
     * @return ProductCategoryLookup1
     */
    public ViewObjectImpl getProductCategoryLookup1() {
        return (ViewObjectImpl) findViewObject("ProductCategoryLookup1");
    }

    /**
     * Container's getter for SuperVisorIdLookup1.
     * @return SuperVisorIdLookup1
     */
    public ViewObjectImpl getSuperVisorIdLookup1() {
        return (ViewObjectImpl) findViewObject("SuperVisorIdLookup1");
    }

    /**
     * Container's getter for ProductsU1.
     * @return ProductsU1
     */
    public ViewObjectImpl getProductsU1() {
        return (ViewObjectImpl) findViewObject("ProductsU1");
    }

    /**
     * Container's getter for ProductsR1.
     * @return ProductsR1
     */
    public ViewObjectImpl getProductsR1() {
        return (ViewObjectImpl) findViewObject("ProductsR1");
    }

    /**
     * Container's getter for UsersRolesU2.
     * @return UsersRolesU2
     */
    public ViewObjectImpl getUsersRolesU2() {
        return (ViewObjectImpl) findViewObject("UsersRolesU2");
    }

    /**
     * Container's getter for UserCount1.
     * @return UserCount1
     */
    public UserCountVOImpl getUserCount1() {
        return (UserCountVOImpl) findViewObject("UserCount1");
    }

    /**
     * Container's getter for ProductCount1.
     * @return ProductCount1
     */
    public ProductCountVOImpl getProductCount1() {
        return (ProductCountVOImpl) findViewObject("ProductCount1");
    }

    /**
     * Container's getter for RoleCount1.
     * @return RoleCount1
     */
    public ViewObjectImpl getRoleCount1() {
        return (ViewObjectImpl) findViewObject("RoleCount1");
    }

    /**
     * Container's getter for LookupsU1.
     * @return LookupsU1
     */
    public ViewObjectImpl getLookupsU1() {
        return (ViewObjectImpl) findViewObject("LookupsU1");
    }

    /**
     * Container's getter for ProductCategoryDefault1.
     * @return ProductCategoryDefault1
     */
    public ViewObjectImpl getProductCategoryDefault1() {
        return (ViewObjectImpl) findViewObject("ProductCategoryDefault1");
    }

    /**
     * Container's getter for RoleNameLookup2.
     * @return RoleNameLookup2
     */
    public ViewObjectImpl getRoleNameLookup2() {
        return (ViewObjectImpl) findViewObject("RoleNameLookup2");
    }

    /**
     * Container's getter for UsersU4.
     * @return UsersU4
     */
    public ViewObjectImpl getUsersU4() {
        return (ViewObjectImpl) findViewObject("UsersU4");
    }

    /**
     * Container's getter for UserRolesMaster1.
     * @return UserRolesMaster1
     */
    public ViewObjectImpl getUserRolesMaster1() {
        return (ViewObjectImpl) findViewObject("UserRolesMaster1");
    }

    /**
     * Container's getter for CustomerTypeLookup1.
     * @return CustomerTypeLookup1
     */
    public ViewObjectImpl getCustomerTypeLookup1() {
        return (ViewObjectImpl) findViewObject("CustomerTypeLookup1");
    }

    /**
     * Container's getter for ContactsU2.
     * @return ContactsU2
     */
    public ViewObjectImpl getContactsU2() {
        return (ViewObjectImpl) findViewObject("ContactsU2");
    }

    /**
     * Container's getter for CustomersU1.
     * @return CustomersU1
     */
    public ViewObjectImpl getCustomersU1() {
        return (ViewObjectImpl) findViewObject("CustomersU1");
    }

    /**
     * Container's getter for CustomersContactsU1.
     * @return CustomersContactsU1
     */
    public ViewObjectImpl getCustomersContactsU1() {
        return (ViewObjectImpl) findViewObject("CustomersContactsU1");
    }

    /**
     * Container's getter for ContactsU3.
     * @return ContactsU3
     */
    public ViewObjectImpl getContactsU3() {
        return (ViewObjectImpl) findViewObject("ContactsU3");
    }

    /**
     * Container's getter for CustomersContactsU2.
     * @return CustomersContactsU2
     */
    public ViewObjectImpl getCustomersContactsU2() {
        return (ViewObjectImpl) findViewObject("CustomersContactsU2");
    }

    /**
     * Container's getter for CustomersContactsU3.
     * @return CustomersContactsU3
     */
    public ViewObjectImpl getCustomersContactsU3() {
        return (ViewObjectImpl) findViewObject("CustomersContactsU3");
    }

    /**
     * Container's getter for ContactsU4.
     * @return ContactsU4
     */
    public ViewObjectImpl getContactsU4() {
        return (ViewObjectImpl) findViewObject("ContactsU4");
    }

    /**
     * Container's getter for CustomersU2.
     * @return CustomersU2
     */
    public ViewObjectImpl getCustomersU2() {
        return (ViewObjectImpl) findViewObject("CustomersU2");
    }

    /**
     * Container's getter for AddressU4.
     * @return AddressU4
     */
    public ViewObjectImpl getAddressU4() {
        return (ViewObjectImpl) findViewObject("AddressU4");
    }

    /**
     * Container's getter for CustomerContactAddressMaster1.
     * @return CustomerContactAddressMaster1
     */
    public ViewObjectImpl getCustomerContactAddressMaster1() {
        return (ViewObjectImpl) findViewObject("CustomerContactAddressMaster1");
    }

    /**
     * Container's getter for RolesLookupMaster1.
     * @return RolesLookupMaster1
     */
    public ViewObjectImpl getRolesLookupMaster1() {
        return (ViewObjectImpl) findViewObject("RolesLookupMaster1");
    }

    /**
     * Container's getter for RolesU3.
     * @return RolesU3
     */
    public ViewObjectImpl getRolesU3() {
        return (ViewObjectImpl) findViewObject("RolesU3");
    }

    /**
     * Container's getter for LookupsU2.
     * @return LookupsU2
     */
    public ViewObjectImpl getLookupsU2() {
        return (ViewObjectImpl) findViewObject("LookupsU2");
    }

    /**
     * Container's getter for BuyingroleLookup1.
     * @return BuyingroleLookup1
     */
    public ViewObjectImpl getBuyingroleLookup1() {
        return (ViewObjectImpl) findViewObject("BuyingroleLookup1");
    }

    /**
     * Container's getter for SalesStageLookup1.
     * @return SalesStageLookup1
     */
    public ViewObjectImpl getSalesStageLookup1() {
        return (ViewObjectImpl) findViewObject("SalesStageLookup1");
    }

    /**
     * Container's getter for SalesMethodLookup1.
     * @return SalesMethodLookup1
     */
    public ViewObjectImpl getSalesMethodLookup1() {
        return (ViewObjectImpl) findViewObject("SalesMethodLookup1");
    }

    /**
     * Container's getter for SalesChannelLookup1.
     * @return SalesChannelLookup1
     */
    public ViewObjectImpl getSalesChannelLookup1() {
        return (ViewObjectImpl) findViewObject("SalesChannelLookup1");
    }

    /**
     * Container's getter for OpportunitiesU1.
     * @return OpportunitiesU1
     */
    public OpportunitiesUVOImpl getOpportunitiesU1() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU1");
    }

    /**
     * Container's getter for ContactsOpportunitiesU1.
     * @return ContactsOpportunitiesU1
     */
    public ViewObjectImpl getContactsOpportunitiesU1() {
        return (ViewObjectImpl) findViewObject("ContactsOpportunitiesU1");
    }

    /**
     * Container's getter for ContactsOpportunitiesU2.
     * @return ContactsOpportunitiesU2
     */
    public ViewObjectImpl getContactsOpportunitiesU2() {
        return (ViewObjectImpl) findViewObject("ContactsOpportunitiesU2");
    }

    /**
     * Container's getter for OpportunitiesU2.
     * @return OpportunitiesU2
     */
    public OpportunitiesUVOImpl getOpportunitiesU2() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU2");
    }

    /**
     * Container's getter for OpportunityDocsU1.
     * @return OpportunityDocsU1
     */
    public ViewObjectImpl getOpportunityDocsU1() {
        return (ViewObjectImpl) findViewObject("OpportunityDocsU1");
    }

    /**
     * Container's getter for OpportunityDocsU2.
     * @return OpportunityDocsU2
     */
    public ViewObjectImpl getOpportunityDocsU2() {
        return (ViewObjectImpl) findViewObject("OpportunityDocsU2");
    }

    /**
     * Container's getter for OpportunitiesU3.
     * @return OpportunitiesU3
     */
    public OpportunitiesUVOImpl getOpportunitiesU3() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU3");
    }

    /**
     * Container's getter for TasksU1.
     * @return TasksU1
     */
    public ViewObjectImpl getTasksU1() {
        return (ViewObjectImpl) findViewObject("TasksU1");
    }

    /**
     * Container's getter for TasksU2.
     * @return TasksU2
     */
    public ViewObjectImpl getTasksU2() {
        return (ViewObjectImpl) findViewObject("TasksU2");
    }

    /**
     * Container's getter for CustomersU6.
     * @return CustomersU6
     */
    public ViewObjectImpl getCustomersU6() {
        return (ViewObjectImpl) findViewObject("CustomersU6");
    }

    /**
     * Container's getter for PrimaryContactLookup1.
     * @return PrimaryContactLookup1
     */
    public ViewObjectImpl getPrimaryContactLookup1() {
        return (ViewObjectImpl) findViewObject("PrimaryContactLookup1");
    }

    /**
     * Container's getter for AddressU5.
     * @return AddressU5
     */
    public ViewObjectImpl getAddressU5() {
        return (ViewObjectImpl) findViewObject("AddressU5");
    }

    /**
     * Container's getter for CustomersU3.
     * @return CustomersU3
     */
    public ViewObjectImpl getCustomersU3() {
        return (ViewObjectImpl) findViewObject("CustomersU3");
    }


    /**
     * Container's getter for CustomersU4.
     * @return CustomersU4
     */
    public ViewObjectImpl getCustomersU4() {
        return (ViewObjectImpl) findViewObject("CustomersU4");
    }

    /**
     * Container's getter for CustomersU5.
     * @return CustomersU5
     */
    public ViewObjectImpl getCustomersU5() {
        return (ViewObjectImpl) findViewObject("CustomersU5");
    }

    /**
     * Container's getter for AddressU6.
     * @return AddressU6
     */
    public ViewObjectImpl getAddressU6() {
        return (ViewObjectImpl) findViewObject("AddressU6");
    }

    /**
     * Container's getter for CustomerId_Address_ViewObj1.
     * @return CustomerId_Address_ViewObj1
     */
    public ViewObjectImpl getCustomerId_Address_ViewObj1() {
        return (ViewObjectImpl) findViewObject("CustomerId_Address_ViewObj1");
    }

    /**
     * Container's getter for UsersRolesU3.
     * @return UsersRolesU3
     */
    public ViewObjectImpl getUsersRolesU3() {
        return (ViewObjectImpl) findViewObject("UsersRolesU3");
    }

    /**
     * Container's getter for OpportunitiesU4.
     * @return OpportunitiesU4
     */
    public OpportunitiesUVOImpl getOpportunitiesU4() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU4");
    }

    /**
     * Container's getter for UsersOpportunitiesU1.
     * @return UsersOpportunitiesU1
     */
    public ViewObjectImpl getUsersOpportunitiesU1() {
        return (ViewObjectImpl) findViewObject("UsersOpportunitiesU1");
    }

    /**
     * Container's getter for OppurtunityDashboardUser1.
     * @return OppurtunityDashboardUser1
     */
    public ViewObjectImpl getOppurtunityDashboardUser1() {
        return (ViewObjectImpl) findViewObject("OppurtunityDashboardUser1");
    }

    /**
     * Container's getter for OppurtunityDashboardUser2.
     * @return OppurtunityDashboardUser2
     */
    public ViewObjectImpl getOppurtunityDashboardUser2() {
        return (ViewObjectImpl) findViewObject("OppurtunityDashboardUser2");
    }

    /**
     * Container's getter for OpportunitiesU5.
     * @return OpportunitiesU5
     */
    public OpportunitiesUVOImpl getOpportunitiesU5() {
        return (OpportunitiesUVOImpl) findViewObject("OpportunitiesU5");
    }

    /**
     * Container's getter for AddressU2.
     * @return AddressU2
     */
    public ViewObjectImpl getAddressU2() {
        return (ViewObjectImpl) findViewObject("AddressU2");
    }

    /**
     * Container's getter for MyTeamR1.
     * @return MyTeamR1
     */
    public ViewObjectImpl getMyTeamR1() {
        return (ViewObjectImpl) findViewObject("MyTeamR1");
    }

    /**
     * Container's getter for UsersRolesU4.
     * @return UsersRolesU4
     */
    public ViewObjectImpl getUsersRolesU4() {
        return (ViewObjectImpl) findViewObject("UsersRolesU4");
    }

    /**
     * Container's getter for UsersFk1VL1.
     * @return UsersFk1VL1
     */
    public ViewLinkImpl getUsersFk1VL1() {
        return (ViewLinkImpl) findViewLink("UsersFk1VL1");
    }

    /**
     * Container's getter for UsersFk1VL2.
     * @return UsersFk1VL2
     */
    public ViewLinkImpl getUsersFk1VL2() {
        return (ViewLinkImpl) findViewLink("UsersFk1VL2");
    }

    /**
     * Container's getter for UserRolesVL.
     * @return UserRolesVL
     */
    public ViewLinkImpl getUserRolesVL() {
        return (ViewLinkImpl) findViewLink("UserRolesVL");
    }

    /**
     * Container's getter for UserRolesVL1.
     * @return UserRolesVL1
     */
    public ViewLinkImpl getUserRolesVL1() {
        return (ViewLinkImpl) findViewLink("UserRolesVL1");
    }

    /**
     * Container's getter for UsersRolesMasterVL1.
     * @return UsersRolesMasterVL1
     */
    public ViewLinkImpl getUsersRolesMasterVL1() {
        return (ViewLinkImpl) findViewLink("UsersRolesMasterVL1");
    }

    /**
     * Container's getter for CustomersContactsFk1VL1.
     * @return CustomersContactsFk1VL1
     */
    public ViewLinkImpl getCustomersContactsFk1VL1() {
        return (ViewLinkImpl) findViewLink("CustomersContactsFk1VL1");
    }

    /**
     * Container's getter for CustomersContactsFk2VL1.
     * @return CustomersContactsFk2VL1
     */
    public ViewLinkImpl getCustomersContactsFk2VL1() {
        return (ViewLinkImpl) findViewLink("CustomersContactsFk2VL1");
    }

    /**
     * Container's getter for CustomersFk1VL1.
     * @return CustomersFk1VL1
     */
    public ViewLinkImpl getCustomersFk1VL1() {
        return (ViewLinkImpl) findViewLink("CustomersFk1VL1");
    }

    /**
     * Container's getter for RolesLookupVL1.
     * @return RolesLookupVL1
     */
    public ViewLinkImpl getRolesLookupVL1() {
        return (ViewLinkImpl) findViewLink("RolesLookupVL1");
    }

    /**
     * Container's getter for ContactsOpportunitiesFk2VL1.
     * @return ContactsOpportunitiesFk2VL1
     */
    public ViewLinkImpl getContactsOpportunitiesFk2VL1() {
        return (ViewLinkImpl) findViewLink("ContactsOpportunitiesFk2VL1");
    }

    /**
     * Container's getter for OpportunityDocsLinkVL1.
     * @return OpportunityDocsLinkVL1
     */
    public ViewLinkImpl getOpportunityDocsLinkVL1() {
        return (ViewLinkImpl) findViewLink("OpportunityDocsLinkVL1");
    }

    /**
     * Container's getter for TasksOppurtunityVL1.
     * @return TasksOppurtunityVL1
     */
    public ViewLinkImpl getTasksOppurtunityVL1() {
        return (ViewLinkImpl) findViewLink("TasksOppurtunityVL1");
    }

    /**
     * Container's getter for RoleFKUserRoleVL1.
     * @return RoleFKUserRoleVL1
     */
    public ViewLinkImpl getRoleFKUserRoleVL1() {
        return (ViewLinkImpl) findViewLink("RoleFKUserRoleVL1");
    }

    /**
     * Container's getter for CustomerPrimaryAddressVL1.
     * @return CustomerPrimaryAddressVL1
     */
    public ViewLinkImpl getCustomerPrimaryAddressVL1() {
        return (ViewLinkImpl) findViewLink("CustomerPrimaryAddressVL1");
    }

    /**
     * Container's getter for CustomerPrimaryAddressVL5.
     * @return CustomerPrimaryAddressVL5
     */
    public ViewLinkImpl getCustomerPrimaryAddressVL5() {
        return (ViewLinkImpl) findViewLink("CustomerPrimaryAddressVL5");
    }

    /**
     * Container's getter for OpportunityDashBoardUserVL.
     * @return OpportunityDashBoardUserVL
     */
    public ViewLinkImpl getOpportunityDashBoardUserVL() {
        return (ViewLinkImpl) findViewLink("OpportunityDashBoardUserVL");
    }


    /**
     * Container's getter for ProdLookupR1.
     * @return ProdLookupR1
     */
    public ViewObjectImpl getProdLookupR1() {
        return (ViewObjectImpl) findViewObject("ProdLookupR1");
    }

    /**
     * Container's getter for LookupProdCatDel1.
     * @return LookupProdCatDel1
     */
    public ViewObjectImpl getLookupProdCatDel1() {
        return (ViewObjectImpl) findViewObject("LookupProdCatDel1");
    }
}

