CREATE OR REPLACE TRIGGER TASKS_TRG 
BEFORE INSERT ON TASKS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TASK_ID IS NULL THEN
      SELECT TASKS_SEQ.NEXTVAL INTO :NEW.TASK_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
